Repository wecode-bootcamp-korea/20-1st-KokoaFriendsMart-frontend, pull requests merged in 2021-05, with the labels that each got.

#3 Add: 초기세팅 추가
  public/index.html
  src/Styles/common.scss
  src/Styles/reset.scss
  src/Styles/variables.scss
Labels: Status: 리뷰 요청

#6 [20기 박준모] Add: mixin.scss, config.js 파일 추가
  src/Styles/_mixin.scss
  src/Styles/_variables.scss
  src/config.js
Labels: Status: Accepted

#4 [20기 이지연] FIx: conflict 해결 후 push
  package-lock.json
  public/data/categoryData.json
  public/images/heart-btn.svg
  public/images/sample.png
  public/images/sprite.png
  public/images/swipe-left-black.svg
  public/images/swipe-left-white.svg
  public/images/swipe-right-black.svg
  public/images/swipe-right-white.svg
  src/Pages/Category/Category.js
  src/Pages/Category/Category.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [20기 이지연] Add: master 브랜치에 images 폴더 추가
  public/images/sample.png
Labels: Status: 리뷰 요청

#5 [20기 조원영] Add: Nav Bar
  public/data/character.json
  public/images/trunk.jpg
  src/Pages/Main/Components/Nav/Characters/Characters.js
  src/Pages/Main/Components/Nav/Characters/Characters.scss
  src/Pages/Main/Components/Nav/CharactersList/CharactersList.js
  src/Pages/Main/Components/Nav/CharactersList/CharactersList.scss
  src/Pages/Main/Components/Nav/Nav.js
  src/Pages/Main/Components/Nav/Nav.scss
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#10 [20기 이지연] Add: ProductItemComponent 추가
  public/data/categoryData.json
  src/Components/ProductItem/ProductItem.js
  src/Components/ProductItem/ProductItem.scss
  src/Components/ProductItem/README.md
  src/Pages/Category/Category.js
Labels: Status: Accepted

#11 [20기 조원영] Nav Bar HTML / CSS 그리고 캐릭터 map 함수 구현
  src/Pages/Category/Category.js
  src/Pages/Main/Components/Nav/Characters/Characters.js
  src/Pages/Main/Components/Nav/Characters/Characters.scss
  src/Pages/Main/Components/Nav/CharactersList/CharactersList.js
  src/Pages/Main/Components/Nav/CharactersList/CharactersList.scss
  src/Pages/Main/Components/Nav/Nav.js
  src/Pages/Main/Components/Nav/Nav.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#12 [20기 이지연] Add: 배너 Arrow 버튼 추가 및 컴포넌트 분리
  src/Pages/Category/Category.js
  src/Pages/Category/Category.scss
  src/Pages/Category/ProductItem.js
  src/Pages/Category/ProductItem.scss
  src/Pages/Main/Components/BestItem/BestItem.js
Labels: Status: Accepted, Status: Conflict 발생

#8 [20기 박준모]Modify: 컨플릭 해결 완료
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Component/Carousel/Carousel.js
  src/Pages/Main/Component/Carousel/Carousel.scss
Labels: Status: Accepted, Status: 리뷰 요청

#15 [20기 이지연] Add: 메인페이지 베스트아이템 섹션 레이아웃 구현 [[멘토님 수정 완료]]
  public/data/categoryData.json
  src/Pages/Main/Components/BestItem/BestItem.js
  src/Pages/Main/Components/BestItem/BestItem.scss
  src/Pages/Main/Components/BestItem/BestProductItem.js
  src/Pages/Main/Components/BestItem/BestProductItem.scss
  src/Pages/Main/Components/BestItem/sprite.png
  src/Pages/Main/Main.js
  src/Styles/variables.scss
Labels: Status: 리뷰 요청

#16 [20기 하연주] Refactor: 멘토 리뷰 반영, Add: 별점 렌더 부분 컴포넌트화
  public/data/electronicImagesData.json
  public/data/livingImagesData.json
  public/data/productInfoData.json
  public/data/reviewData.json
  public/data/wearImagesData.json
  public/images/stars/star-half-line-sm-gray.svg
  public/images/stars/star-off-line-sm-gray.svg
  public/images/stars/star-off-line-sm.svg
  public/images/stars/star-on-line-sm-gray.svg
  public/images/stars/star-on-line-sm.svg
  src/Pages/Main/Components/Nav/Nav.scss
  src/Pages/Product/Product.js
  src/Pages/Product/Product.scss
  src/Pages/Product/components/ProductDetail/ProductDetail.js
  src/Pages/Product/components/ProductDetail/ProductDetail.scss
  src/Pages/Product/components/ProductOption/ProductOption.js
  src/Pages/Product/components/ProductOption/ProductOption.scss
  src/Pages/Product/components/ProductQna/ProductQna.js
  src/Pages/Product/components/ProductQna/ProductQna.scss
  src/Pages/Product/components/ProductReview/Components/StarRatyGrey/StarRatyGrey.js
  src/Pages/Product/components/ProductReview/Components/StarRatyGrey/StarRatyGrey.scss
  src/Pages/Product/components/ProductReview/Components/StarRatyYellow/StarRatyYellow.js
  src/Pages/Product/components/ProductReview/Components/StarRatyYellow/StarRatyYellow.scss
  src/Pages/Product/components/ProductReview/ProductReview.js
  src/Pages/Product/components/ProductReview/ProductReview.scss
Labels: Status: 리뷰 요청

#22 [20기 박준모] footer Modify: 컨플릭 해결
  src/Pages/Footer/Footer.js
  src/Pages/Footer/Footer.scss
  src/Routes.js
Labels: Status: Accepted

#23 [20기 하연주]Add: 상세페이지 라우팅 기능 / dangerouslySetInnerHTML로 태그 추가/품절상품 버튼 비활성화
  public/data/productInfoData.json
  src/Pages/Cart/Components/ProductInCart/ProductInCart.scss
  src/Pages/Product/Product.js
  src/Pages/Product/Product.scss
  src/Pages/Product/components/ProductDetail/ProductDetail.js
  src/Pages/Product/components/ProductDetail/ProductDetail.scss
  src/Pages/Product/components/ProductOption/ProductOption.js
Labels: Status: Accepted

#25 [20기 박준모] Feature/orderlist 레이아웃 완료
  src/Pages/Orderlist/OrderItem.js
  src/Pages/Orderlist/OrderListData.js
  src/Pages/Orderlist/Orderlist.js
  src/Pages/Orderlist/Orderlist.scss
  src/Pages/Payment/OrderProductIItem.js
  src/Routes.js
Labels: Status: 리뷰 요청

#14 [20기 조원영] Main page MD's Pick 레이아웃 구현
  public/data/categoryData.json
  public/images/treeTablet.png
  src/Components/ProductItem/ProductItem.js
  src/Components/ProductItem/ProductItem.scss
  src/Pages/Category/Category.js
  src/Pages/Category/ProductItem.js
  src/Pages/Category/ProductItem.scss
  src/Pages/Main/Components/BestItem/BestProductItem.js
  src/Pages/Main/Components/BestItem/BestProductItem.scss
  src/Pages/Main/Components/Mdpick/Mdpick.js
  src/Pages/Main/Components/Mdpick/Mdpick.scss
  src/Pages/Main/Main.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#19 [20기 이지연] 멘토님 리뷰 반영 및 쿼리스트링 분해 질문하기, 페이지네이션 구현 완료 및 페이지네이션 키값 에러 해결 질문
  public/data/bestItemData.json
  src/Components/ProductItem/ProductItem.js
  src/Components/ProductItem/ProductItem.scss
  src/Pages/Category/Category.js
  src/Pages/Category/Category.scss
  src/Pages/Main/Components/Nav/Characters/Characters.js
  src/Pages/Product/Product.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#17 [20기 박준모] Carousel Modify: 컨플릭 해결
  .vscode/launch.json
  public/images/bluebg.png
  public/images/pinkbg.png
  public/images/yellowbg.png
  src/Pages/Main/Component/Carousel/Carousel.js
  src/Pages/Main/Components/Carousel/Carousel.js
  src/Pages/Main/Components/Carousel/Carousel.scss
  src/Pages/Main/Components/Carousel/CarouselCard.js
  src/Pages/Main/Components/Carousel/CarouselData.js
  src/Pages/Main/Main.js
Labels: Status: Accepted

#20 [20기 박준모] 주문하기 page Modify: 컨플릭 해결
  public/data/cartData.json
  src/Pages/Payment/OrderProductIItem.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#29 [20기 하연주] Add: 장바구니 기능구현
  public/data/cartProductData.json
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/Components/CheckBoxHeader/CheckBoxHeader.js
  src/Pages/Cart/Components/CheckBoxHeader/CheckBoxHeader.scss
  src/Pages/Cart/Components/ProductInCart/ProductInCart.js
  src/Pages/Cart/Components/ProductInCart/ProductInCart.scss
  src/Pages/Cart/Components/TotalPriceBox/TotalPriceBox.js
  src/Pages/Product/components/ProductOption/ProductOption.js
Labels: Status: Accepted

#30 [20기 조원영] Main Page - MD's Pick 그리고 Best Pick Fetch기능 수정 했습니다!
  public/data/categoryData.json
  src/Pages/Main/Components/BestItem/BestItem.js
  src/Pages/Main/Components/BestItem/BestProductItem.js
  src/Pages/Main/Components/Mdpick/Mdpick.js
  src/Pages/Product/Product.js
Labels: Status: 리뷰 요청

#28 [20기 조원영] 메인페이지 Best Pick
  public/data/bestItemData.json
  src/Pages/Category/Category.js
  src/Pages/Category/Category.scss
  src/Pages/Main/Components/BestItem/BestItem.js
  src/Pages/Main/Components/BestItem/BestItem.scss
  src/Pages/Main/Components/BestItem/BestProductItem.scss
  src/Pages/Main/Components/LikePick/LikePick.scss
  src/Pages/Main/Components/Mdpick/Mdpick.scss
  src/Pages/Main/Components/Nav/CharactersList/CharactersList.scss
  src/Pages/Product/Product.js
  src/Pages/Product/components/ProductOption/ProductOption.js
  src/Pages/Product/components/ProductReview/ProductReview.js
  src/Routes.js
Labels: Status: 리뷰 요청

#31 [20기 이지연] Modify: 캐릭터 배너 만들기 & 상품개수 삭제
  src/Pages/Category/Category.js
  src/Pages/Main/Components/Nav/Search.scss
Labels: Status: 리뷰 요청

#32 [20기 조원영] 로그인 / 로그아웃 상태변화
  src/Pages/Main/Components/Nav/Nav.js
Labels: Status: 리뷰 요청

#33 [20기 조원영] Nav Bar CSS 수정 및 카트 링크 걸어주었습니다
  src/Pages/Main/Components/Nav/Nav.js
  src/Pages/Main/Components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#34 [20기 조원영] 메인 페이지 Carousel CSS Update
  src/Pages/Main/Components/Carousel/Carousel.scss
Labels: Status: 리뷰 요청

#35 [20기 박준모] 결제하기 페이지 Modify: 마지막 커밋
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
Labels: Status: 리뷰 요청

#41 [20기 하연주] Fix: 장바구니 오류 수정
  src/Pages/Cart/Cart.js
  src/Pages/Payment/Payment.js
  src/Pages/Product/Product.js
  src/Pages/Product/components/ProductOption/ProductOption.js
  src/Pages/Product/components/ProductOption/ProductOption.scss
Labels: Status: 리뷰 요청

#42 [20기 하연주] Fix: 테스트 중 페이지 이동 오류 수정
  src/Pages/Main/Components/Nav/Characters/Characters.js
  src/Pages/Payment/Payment.js
Labels: Status: 리뷰 요청
